apiVersion: v1
kind: Service
metadata:
  name: nginx-gitops-service
  namespace: default
spec:
  selector:
    app: nginx-gitops  # This MUST match the label in your deployment
  ports:
    - protocol: TCP
      port: 80         # The port the service listens on
      targetPort: 80   # The port the POD is listening on
  type: LoadBalancer
